#!/bin/bash

# tool name
# TOOL_NAME="mlab-to-extxyz"

# TARGET_PATH="/home/$USER/.local/bin/mlab-to-extxyz-parser"
TARGET_PATH="/home/opt/mlab-to-extxyz-parser"
LINK_PATH="/usr/local/bin/mlab-to-extxyz"

# make source executable
chmod +x mlab-to-extxyz.py

# remove the .py form the file name
cp mlab-to-extxyz.py mlab-to-extxyz

if [ -d $TARGET_PATH ]; then
  sudo rm -rf $TARGET_PATH
fi

# create source directory
sudo mkdir -p $TARGET_PATH
 
# copy the source files to the source directory
sudo cp *.py $TARGET_PATH/
sudo cp mlab-to-extxyz $TARGET_PATH/mlab-to-extxyz

if [ ! -d $LINK_PATH ]; then
  sudo rm $LINK_PATH
fi

# add symblic link to the binary
sudo ln -s $TARGET_PATH/mlab-to-extxyz $LINK_PATH